# Generated by Django 5.2.9 on 2026-08-23 21:38

import django.core.validators
import django.utils.timezone
from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Sert à la connexion et à la recherche sociale.",
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le nom d'utilisateur ne peut contenir que des lettres, chiffres et les caractères . @ + - _",
                                regex="^[\\w.@+-]+$",
                            )
                        ],
                        verbose_name="nom d'utilisateur",
                    ),
                ),
                (
                    "normalized_username",
                    models.CharField(
                        editable=False,
                        help_text="Forme minuscule garantissant l'unicité insensible à la casse.",
                        max_length=30,
                        unique=True,
                        verbose_name="nom d'utilisateur normalisé",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Facultatif. Jamais utilisé pour la recherche sociale.",
                        max_length=254,
                        null=True,
                        verbose_name="adresse email",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, verbose_name="prénom")),
                ("last_name", models.CharField(blank=True, max_length=100, verbose_name="nom")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACTIVE", "Actif"),
                            ("SUSPENDED", "Suspendu"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                        verbose_name="statut",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Autorise l'accès à l'administration Django.",
                        verbose_name="membre de l'équipe",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, verbose_name="créé le"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
                "ordering": ["username"],
            },
            managers=[
                ("objects", accounts.models.UserManager()),
            ],
        ),
    ]
