# Generated by Django 5.2.9 on 2026-08-23 22:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "username",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le nom d'utilisateur ne peut contenir que des lettres, chiffres et les caractères . @ + - _",
                                regex="^[\\w.@+-]+$",
                            )
                        ],
                        verbose_name="nom d'utilisateur",
                    ),
                ),
                (
                    "normalized_username",
                    models.CharField(
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="nom d'utilisateur normalisé",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="adresse email"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        editable=False, max_length=128, verbose_name="mot de passe haché"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False, verbose_name="demandé le"
                    ),
                ),
            ],
            options={
                "verbose_name": "demande d'inscription",
                "verbose_name_plural": "demandes d'inscription",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="token_version",
            field=models.PositiveIntegerField(
                default=1,
                editable=False,
                help_text="Incrémentée pour révoquer immédiatement tous les tokens émis précédemment (déconnexion globale, changement de mot de passe, suspension).",
                verbose_name="version de session",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="date de naissance"),
                ),
                (
                    "sex_for_calculation",
                    models.CharField(
                        blank=True,
                        choices=[("FEMALE", "Femme"), ("MALE", "Homme")],
                        max_length=16,
                        null=True,
                        verbose_name="sexe utilisé pour le calcul",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="taille (cm)",
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SEDENTARY", "Sédentaire"),
                            ("LIGHTLY_ACTIVE", "Légèrement actif"),
                            ("MODERATELY_ACTIVE", "Modérément actif"),
                            ("VERY_ACTIVE", "Très actif"),
                            ("EXTREMELY_ACTIVE", "Extrêmement actif"),
                        ],
                        max_length=24,
                        null=True,
                        verbose_name="niveau d'activité",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        blank=True,
                        choices=[("LOSS", "Perte"), ("MAINTENANCE", "Maintien"), ("GAIN", "Prise")],
                        max_length=16,
                        null=True,
                        verbose_name="objectif",
                    ),
                ),
                (
                    "goal_rate_kg_per_week",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="rythme (kg/semaine)",
                    ),
                ),
                (
                    "target_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="poids cible (kg)",
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(default=False, verbose_name="onboarding terminé"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil",
                "verbose_name_plural": "profils",
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("language", models.CharField(default="fr", max_length=5, verbose_name="langue")),
                (
                    "theme_mode",
                    models.CharField(
                        choices=[("light", "Clair"), ("dark", "Sombre"), ("system", "Système")],
                        default="system",
                        max_length=8,
                        verbose_name="thème",
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="DD/MM/YYYY", max_length=20, verbose_name="format de date"
                    ),
                ),
                (
                    "dashboard_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="configuration du dashboard"
                    ),
                ),
                (
                    "privacy_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="configuration de confidentialité"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "paramètres",
                "verbose_name_plural": "paramètres",
            },
        ),
    ]
