# Generated by Django 5.2.9 on 2026-08-23 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_registrationrequest_user_token_version_userprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationrequest",
            name="username",
            field=models.CharField(
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le nom d’utilisateur ne peut contenir que des lettres, chiffres et les caractères . @ + - _",
                        regex="^[\\w.@+-]+$",
                    )
                ],
                verbose_name="nom d'utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Sert à la connexion et à la recherche sociale.",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le nom d’utilisateur ne peut contenir que des lettres, chiffres et les caractères . @ + - _",
                        regex="^[\\w.@+-]+$",
                    )
                ],
                verbose_name="nom d'utilisateur",
            ),
        ),
    ]
