# Generated by Django 5.2.9 on 2026-08-28 11:55

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_update_username_validator_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="food_search_languages",
            field=models.JSONField(
                blank=True,
                default=accounts.models.default_food_search_languages,
                help_text="Langues interrogées lors d'une recherche de produits de marque. Open Food Facts indexe les noms par langue : sans le suédois, un produit nommé en suédois reste introuvable.",
                verbose_name="langues de recherche de produits",
            ),
        ),
    ]
