# Generated by Django 5.2.9 on 2026-08-25 12:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "daily_calories",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="calories quotidiennes"
                    ),
                ),
                (
                    "protein_g",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="protéines (g)"
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="glucides (g)"
                    ),
                ),
                (
                    "fat_g",
                    models.DecimalField(decimal_places=2, max_digits=6, verbose_name="lipides (g)"),
                ),
                (
                    "fiber_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="fibres (g)",
                    ),
                ),
                (
                    "macro_mode",
                    models.CharField(
                        choices=[("percentage", "Pourcentage"), ("grams", "Grammes")],
                        default="percentage",
                        max_length=16,
                        verbose_name="mode des macros",
                    ),
                ),
                (
                    "calories_source",
                    models.CharField(
                        choices=[("calculated", "Calculé"), ("manual", "Manuel")],
                        default="calculated",
                        max_length=16,
                        verbose_name="origine des calories",
                    ),
                ),
                (
                    "macros_source",
                    models.CharField(
                        choices=[("calculated", "Calculé"), ("manual", "Manuel")],
                        default="calculated",
                        max_length=16,
                        verbose_name="origine des macros",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="applicable à partir du")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Nul tant que l'objectif est celui en cours.",
                        null=True,
                        verbose_name="applicable jusqu'au",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "objectif nutritionnel",
                "verbose_name_plural": "objectifs nutritionnels",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="NutritionGoalDayOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        help_text="0 = lundi, 6 = dimanche.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="jour de la semaine",
                    ),
                ),
                (
                    "daily_calories",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="calories quotidiennes",
                    ),
                ),
                (
                    "protein_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="protéines (g)",
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="glucides (g)",
                    ),
                ),
                (
                    "fat_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="lipides (g)",
                    ),
                ),
                (
                    "fiber_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="fibres (g)",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="activée")),
                (
                    "nutrition_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_overrides",
                        to="nutrition.nutritiongoal",
                        verbose_name="objectif",
                    ),
                ),
            ],
            options={
                "verbose_name": "surcharge de jour",
                "verbose_name_plural": "surcharges de jour",
                "ordering": ["weekday"],
            },
        ),
        migrations.AddIndex(
            model_name="nutritiongoal",
            index=models.Index(
                fields=["user", "-start_date"], name="nutrition_n_user_id_2c4529_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritiongoal",
            constraint=models.UniqueConstraint(
                fields=("user", "start_date"), name="nutrition_goal_unique_start_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritiongoal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("end_date__isnull", True)),
                fields=("user",),
                name="nutrition_goal_single_open_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritiongoal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="nutrition_goal_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritiongoal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("daily_calories__gte", 0),
                    ("protein_g__gte", 0),
                    ("carbs_g__gte", 0),
                    ("fat_g__gte", 0),
                ),
                name="nutrition_goal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritiongoaldayoverride",
            constraint=models.UniqueConstraint(
                fields=("nutrition_goal", "weekday"), name="nutrition_goal_override_unique_weekday"
            ),
        ),
        migrations.AddConstraint(
            model_name="nutritiongoaldayoverride",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                name="nutrition_goal_override_weekday_range",
            ),
        ),
    ]
