# Generated by Django 5.2.9 on 2026-08-25 16:54

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "brand",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="marque"),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=32,
                        null=True,
                        verbose_name="code-barres",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ciqual", "Ciqual"),
                            ("off", "Open Food Facts"),
                            ("user", "Utilisateur"),
                            ("generated", "Généré"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="source",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Privé"),
                            ("specific_users", "Utilisateurs choisis"),
                            ("app_users", "Tous les utilisateurs actifs"),
                        ],
                        default="private",
                        max_length=16,
                        verbose_name="visibilité",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Code Ciqual ou identifiant Open Food Facts.",
                        max_length=64,
                        null=True,
                        verbose_name="identifiant externe",
                    ),
                ),
                (
                    "default_unit_type",
                    models.CharField(
                        choices=[("g", "Grammes"), ("ml", "Millilitres"), ("unit", "Unité")],
                        default="g",
                        max_length=8,
                        verbose_name="type d'unité",
                    ),
                ),
                (
                    "reference_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=7,
                        verbose_name="quantité de référence",
                    ),
                ),
                (
                    "reference_unit",
                    models.CharField(
                        choices=[("g", "Grammes"), ("ml", "Millilitres"), ("unit", "Unité")],
                        default="g",
                        max_length=8,
                        verbose_name="unité de référence",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False, verbose_name="vérifié")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "search_text",
                    models.TextField(default="", editable=False, verbose_name="texte de recherche"),
                ),
                (
                    "external_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="mis à jour à la source le"
                    ),
                ),
                (
                    "cache_refreshed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="cache rafraîchi le"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Suppression douce : les entrées de journal historiques restent valides.",
                        null=True,
                        verbose_name="supprimé le",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obligatoire pour un aliment créé par un utilisateur.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propriétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "aliment",
                "verbose_name_plural": "aliments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FoodNutrition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "energy_kcal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="énergie (kcal)",
                    ),
                ),
                (
                    "protein_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="protéines (g)",
                    ),
                ),
                (
                    "carbohydrates_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="glucides (g)",
                    ),
                ),
                (
                    "fat_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="lipides (g)",
                    ),
                ),
                (
                    "fiber_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="fibres (g)",
                    ),
                ),
                (
                    "sugars_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="sucres (g)",
                    ),
                ),
                (
                    "sodium_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="sodium (mg)",
                    ),
                ),
                (
                    "salt_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="sel (g)",
                    ),
                ),
                (
                    "cholesterol_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="cholestérol (mg)",
                    ),
                ),
                (
                    "potassium_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="potassium (mg)",
                    ),
                ),
                (
                    "calcium_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="calcium (mg)",
                    ),
                ),
                (
                    "iron_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="fer (mg)",
                    ),
                ),
                (
                    "magnesium_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="magnésium (mg)",
                    ),
                ),
                (
                    "vitamin_a_ug",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine A (µg)",
                    ),
                ),
                (
                    "vitamin_b6_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine B6 (mg)",
                    ),
                ),
                (
                    "vitamin_b12_ug",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine B12 (µg)",
                    ),
                ),
                (
                    "vitamin_c_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine C (mg)",
                    ),
                ),
                (
                    "vitamin_d_ug",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine D (µg)",
                    ),
                ),
                (
                    "vitamin_e_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine E (mg)",
                    ),
                ),
                (
                    "vitamin_k_ug",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine K (µg)",
                    ),
                ),
                (
                    "food",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition",
                        to="nutrition.food",
                        verbose_name="aliment",
                    ),
                ),
            ],
            options={
                "verbose_name": "valeurs nutritionnelles",
                "verbose_name_plural": "valeurs nutritionnelles",
            },
        ),
        migrations.CreateModel(
            name="FoodPortion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "gram_equivalent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="équivalent en grammes",
                    ),
                ),
                (
                    "milliliter_equivalent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="équivalent en millilitres",
                    ),
                ),
                (
                    "unit_equivalent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="équivalent en unités",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="portion par défaut"),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="ordre")),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portions",
                        to="nutrition.food",
                        verbose_name="aliment",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nul pour une portion officielle, sinon portion privée à cet utilisateur.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_portions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propriétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "portion",
                "verbose_name_plural": "portions",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserFoodFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="nutrition.food",
                        verbose_name="aliment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "aliment favori",
                "verbose_name_plural": "aliments favoris",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFoodHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("last_used_at", models.DateTimeField(verbose_name="dernière utilisation")),
                (
                    "use_count",
                    models.PositiveIntegerField(default=1, verbose_name="nombre d'utilisations"),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_history",
                        to="nutrition.food",
                        verbose_name="aliment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "historique d'aliment",
                "verbose_name_plural": "historiques d'aliments",
                "ordering": ["-last_used_at"],
            },
        ),
        migrations.AddIndex(
            model_name="food",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_text"], name="food_search_text_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                django.db.models.functions.text.Lower("name"), name="food_name_lower"
            ),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["owner", "-updated_at"], name="food_owner_updated"),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__isnull", False)),
                fields=("source", "external_id"),
                name="food_unique_external_id_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source", "user"), _negated=True),
                    ("owner__isnull", False),
                    _connector="OR",
                ),
                name="food_user_source_requires_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="food",
            constraint=models.CheckConstraint(
                condition=models.Q(("reference_amount__gt", 0)),
                name="food_reference_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="foodportion",
            constraint=models.UniqueConstraint(
                fields=("food", "owner", "name"), name="food_portion_unique_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="foodportion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gram_equivalent__isnull", False),
                    ("milliliter_equivalent__isnull", False),
                    ("unit_equivalent__isnull", False),
                    _connector="OR",
                ),
                name="food_portion_requires_equivalent",
            ),
        ),
        migrations.AddConstraint(
            model_name="userfoodfavorite",
            constraint=models.UniqueConstraint(
                fields=("user", "food"), name="user_food_favorite_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="userfoodhistory",
            index=models.Index(fields=["user", "-last_used_at"], name="food_history_recent"),
        ),
        migrations.AddIndex(
            model_name="userfoodhistory",
            index=models.Index(fields=["user", "-use_count"], name="food_history_frequent"),
        ),
        migrations.AddConstraint(
            model_name="userfoodhistory",
            constraint=models.UniqueConstraint(
                fields=("user", "food"), name="user_food_history_unique"
            ),
        ),
    ]
