# Generated by Django 5.2.9 on 2026-08-25 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0002_food_foodnutrition_foodportion_userfoodfavorite_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="foodportion",
            name="food_portion_unique_name",
        ),
        migrations.AddConstraint(
            model_name="foodportion",
            constraint=models.UniqueConstraint(
                fields=("food", "owner", "name"),
                name="food_portion_unique_name",
                nulls_distinct=False,
            ),
        ),
    ]
