# Generated by Django 5.2.9 on 2026-08-23 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("ACCOUNT_ACCEPTED", "Compte accepté"),
                            ("ACCOUNT_REJECTED", "Compte refusé"),
                            ("PASSWORD_RESET", "Réinitialisation du mot de passe"),
                        ],
                        max_length=32,
                        verbose_name="type",
                    ),
                ),
                ("recipient", models.EmailField(max_length=254, verbose_name="destinataire")),
                (
                    "status",
                    models.CharField(
                        choices=[("SENT", "Envoyé"), ("FAILED", "Échec")],
                        max_length=8,
                        verbose_name="statut",
                    ),
                ),
                (
                    "provider_response_summary",
                    models.TextField(
                        blank=True,
                        help_text="Résumé nettoyé, utilisé pour diagnostiquer un échec.",
                        null=True,
                        verbose_name="réponse du fournisseur",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="envoyé le")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nul lorsque l'email ne correspond à aucun compte, par exemple un refus.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "email envoyé",
                "verbose_name_plural": "emails envoyés",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email_type", "-created_at"], name="notificatio_email_t_e9837a_idx"
                    )
                ],
            },
        ),
    ]
