# Generated by Django 5.2.9 on 2026-08-30 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import notifications.models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("ACCOUNT_ACCEPTED", "Compte accepté"),
                    ("ACCOUNT_REJECTED", "Compte refusé"),
                    ("PASSWORD_RESET", "Réinitialisation du mot de passe"),
                    ("NOTIFICATION", "Notification"),
                ],
                max_length=32,
                verbose_name="type",
            ),
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("meal", "Repas"),
                            ("weigh_in", "Pesée"),
                            ("plan", "Planification"),
                        ],
                        max_length=16,
                        verbose_name="type",
                    ),
                ),
                ("time", models.TimeField(verbose_name="heure")),
                (
                    "days_of_week",
                    models.JSONField(
                        default=notifications.models.all_weekdays,
                        help_text="Entiers de 0 (lundi) à 6 (dimanche), convention Python.",
                        verbose_name="jours de la semaine",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="actif")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "rappel",
                "verbose_name_plural": "rappels",
                "ordering": ["reminder_type"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meal_reminder", "Rappel de repas"),
                            ("weigh_in_reminder", "Rappel de pesée"),
                            ("plan_reminder", "Rappel de planification"),
                            ("friend_request", "Demande d'ami reçue"),
                            ("friend_accepted", "Demande d'ami acceptée"),
                            ("share_received", "Partage reçu"),
                        ],
                        max_length=32,
                        verbose_name="événement",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="titre")),
                (
                    "message",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="message"
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="Chemin interne de l'application, jamais une URL externe.",
                        max_length=255,
                        null=True,
                        verbose_name="lien",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="lue")),
                (
                    "scheduled_on",
                    models.DateField(
                        blank=True,
                        help_text="Date du rappel. Avec le rappel, forme la clé d'unicité.",
                        null=True,
                        verbose_name="journée visée",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Renseigné quand la notification vient d'un rappel planifié.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifications.reminder",
                        verbose_name="rappel",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meal_reminder", "Rappel de repas"),
                            ("weigh_in_reminder", "Rappel de pesée"),
                            ("plan_reminder", "Rappel de planification"),
                            ("friend_request", "Demande d'ami reçue"),
                            ("friend_accepted", "Demande d'ami acceptée"),
                            ("share_received", "Partage reçu"),
                        ],
                        max_length=32,
                        verbose_name="événement",
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(default=True, verbose_name="dans l'application"),
                ),
                ("email_enabled", models.BooleanField(default=False, verbose_name="par email")),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="La colonne existe (spec 03 §11) ; aucun canal ne la lit encore.",
                        verbose_name="par notification push",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "préférence de notification",
                "verbose_name_plural": "préférences de notification",
                "ordering": ["event_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "event_type"),
                        name="notification_preference_unique_per_event",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(fields=["enabled", "time"], name="notificatio_enabled_962859_idx"),
        ),
        migrations.AddConstraint(
            model_name="reminder",
            constraint=models.UniqueConstraint(
                fields=("user", "reminder_type"), name="reminder_unique_per_type"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"], name="notificatio_user_id_f2ad08_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reminder__isnull", False)),
                fields=("reminder", "scheduled_on"),
                name="notification_reminder_once_per_day",
            ),
        ),
    ]
