# Generated by Django 5.2.9 on 2026-08-25 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nutrition", "0003_fix_food_portion_unique_nulls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                ("notes", models.TextField(blank=True, default="", verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diary_days",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "journée",
                "verbose_name_plural": "journées",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MealType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "system_key",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("breakfast", "Petit-déjeuner"),
                            ("lunch", "Déjeuner"),
                            ("dinner", "Dîner"),
                            ("snacks", "Collations"),
                        ],
                        help_text="Renseignée pour les quatre repas par défaut.",
                        max_length=16,
                        null=True,
                        verbose_name="clé système",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="nom")),
                ("slug", models.SlugField(max_length=60, verbose_name="identifiant")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="ordre")),
                ("is_default", models.BooleanField(default=False, verbose_name="repas par défaut")),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_types",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "type de repas",
                "verbose_name_plural": "types de repas",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("food", "Aliment"),
                            ("recipe", "Recette"),
                            ("quick_add", "Ajout rapide"),
                        ],
                        default="food",
                        max_length=16,
                        verbose_name="type",
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        help_text="Horodaté automatiquement à l'ajout, modifiable ensuite.",
                        verbose_name="consommé à",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, max_digits=10, verbose_name="quantité"),
                ),
                ("unit_label", models.CharField(max_length=40, verbose_name="unité")),
                (
                    "note",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="note"),
                ),
                ("snapshot_name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "snapshot_brand",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="marque"),
                ),
                ("snapshot_source", models.CharField(max_length=16, verbose_name="source")),
                (
                    "snapshot_reference_amount",
                    models.DecimalField(
                        decimal_places=3,
                        default=100,
                        max_digits=10,
                        verbose_name="quantité de référence",
                    ),
                ),
                (
                    "snapshot_reference_unit",
                    models.CharField(
                        choices=[("g", "Grammes"), ("ml", "Millilitres"), ("unit", "Unité")],
                        default="g",
                        max_length=8,
                        verbose_name="unité de référence",
                    ),
                ),
                (
                    "snapshot_unit_factor",
                    models.DecimalField(
                        decimal_places=4,
                        default=1,
                        help_text="Combien d'unités de référence vaut une unité saisie. Figé à l'ajout pour que l'entrée reste calculable même si l'aliment ou sa portion disparaît.",
                        max_digits=12,
                        verbose_name="valeur d'une unité saisie",
                    ),
                ),
                (
                    "snapshot_energy_kcal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="énergie (kcal)",
                    ),
                ),
                (
                    "snapshot_protein_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="protéines (g)",
                    ),
                ),
                (
                    "snapshot_carbohydrates_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="glucides (g)",
                    ),
                ),
                (
                    "snapshot_fat_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="lipides (g)",
                    ),
                ),
                (
                    "snapshot_fiber_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="fibres (g)",
                    ),
                ),
                (
                    "snapshot_sugars_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="sucres (g)",
                    ),
                ),
                (
                    "snapshot_sodium_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="sodium (mg)",
                    ),
                ),
                (
                    "snapshot_salt_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="sel (g)",
                    ),
                ),
                (
                    "snapshot_cholesterol_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="cholestérol (mg)",
                    ),
                ),
                (
                    "snapshot_potassium_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="potassium (mg)",
                    ),
                ),
                (
                    "snapshot_calcium_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="calcium (mg)",
                    ),
                ),
                (
                    "snapshot_iron_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="fer (mg)",
                    ),
                ),
                (
                    "snapshot_magnesium_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="magnésium (mg)",
                    ),
                ),
                (
                    "snapshot_vitamin_a_ug",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine A (µg)",
                    ),
                ),
                (
                    "snapshot_vitamin_b6_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine B6 (mg)",
                    ),
                ),
                (
                    "snapshot_vitamin_b12_ug",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine B12 (µg)",
                    ),
                ),
                (
                    "snapshot_vitamin_c_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine C (mg)",
                    ),
                ),
                (
                    "snapshot_vitamin_d_ug",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine D (µg)",
                    ),
                ),
                (
                    "snapshot_vitamin_e_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine E (mg)",
                    ),
                ),
                (
                    "snapshot_vitamin_k_ug",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine K (µg)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "diary_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="diary.diaryday",
                        verbose_name="journée",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diary_entries",
                        to="nutrition.food",
                        verbose_name="aliment",
                    ),
                ),
                (
                    "meal_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="diary.mealtype",
                        verbose_name="repas",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrée de journal",
                "verbose_name_plural": "entrées de journal",
                "ordering": ["consumed_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="diaryday",
            index=models.Index(fields=["user", "-date"], name="diary_day_user_date"),
        ),
        migrations.AddConstraint(
            model_name="diaryday",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="diary_day_unique_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="mealtype",
            constraint=models.UniqueConstraint(
                fields=("user", "slug"), name="meal_type_unique_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="diaryentry",
            index=models.Index(fields=["diary_day", "meal_type"], name="diary_entry_day_meal"),
        ),
        migrations.AddConstraint(
            model_name="diaryentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="diary_entry_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="diaryentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("snapshot_reference_amount__gt", 0)),
                name="diary_entry_reference_amount_positive",
            ),
        ),
    ]
