# Generated by Django 5.2.9 on 2026-08-26 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="meal_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="diary.mealtype",
                verbose_name="repas",
            ),
        ),
    ]
