# Generated by Django 5.2.9 on 2026-08-27 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0002_alter_diaryentry_meal_type"),
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diary_entries",
                to="recipes.recipe",
                verbose_name="recette",
            ),
        ),
    ]
