# Generated by Django 5.2.9 on 2026-08-27 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nutrition", "0003_fix_food_portion_unique_nulls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Privé"),
                            ("specific_users", "Utilisateurs choisis"),
                            ("app_users", "Tous les utilisateurs actifs"),
                        ],
                        default="private",
                        max_length=16,
                        verbose_name="visibilité",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifiée le")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propriétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "liste de courses",
                "verbose_name_plural": "listes de courses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="quantité",
                    ),
                ),
                (
                    "unit_label",
                    models.CharField(blank=True, max_length=40, null=True, verbose_name="unité"),
                ),
                ("is_checked", models.BooleanField(default=False, verbose_name="acheté")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Ajouté à la main"),
                            ("recipe", "Recette"),
                            ("meal_plan", "Planning"),
                            ("diary", "Journal"),
                        ],
                        default="manual",
                        max_length=16,
                        verbose_name="provenance",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_items",
                        to="nutrition.food",
                        verbose_name="aliment",
                    ),
                ),
                (
                    "shopping_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="planning.shoppinglist",
                        verbose_name="liste",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="shoppinglist",
            index=models.Index(fields=["owner", "-created_at"], name="shopping_list_owner"),
        ),
        migrations.AddConstraint(
            model_name="shoppinglistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity__isnull", True), ("quantity__gt", 0), _connector="OR"
                ),
                name="shopping_item_positive_quantity",
            ),
        ),
    ]
