# Generated by Django 5.2.9 on 2026-08-28 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0003_diaryentry_recipe"),
        ("nutrition", "0003_fix_food_portion_unique_nulls"),
        ("planning", "0001_initial"),
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                ("start_date", models.DateField(verbose_name="début")),
                ("end_date", models.DateField(verbose_name="fin")),
                (
                    "generated_by_ai",
                    models.BooleanField(default=False, verbose_name="généré par IA"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propriétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "planning",
                "verbose_name_plural": "plannings",
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MealPlanDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="planning.mealplan",
                        verbose_name="planning",
                    ),
                ),
            ],
            options={
                "verbose_name": "journée planifiée",
                "verbose_name_plural": "journées planifiées",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="MealPlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("food", "Aliment"),
                            ("recipe", "Recette"),
                            ("saved_meal", "Repas enregistré"),
                        ],
                        max_length=16,
                        verbose_name="type",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, max_digits=10, verbose_name="quantité"),
                ),
                ("unit_label", models.CharField(max_length=40, verbose_name="unité")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "generated_by_ai",
                    models.BooleanField(default=False, verbose_name="proposé par IA"),
                ),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_plan_entries",
                        to="nutrition.food",
                        verbose_name="aliment",
                    ),
                ),
                (
                    "meal_plan_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="planning.mealplanday",
                        verbose_name="journée",
                    ),
                ),
                (
                    "meal_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plan_entries",
                        to="diary.mealtype",
                        verbose_name="repas",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_plan_entries",
                        to="recipes.recipe",
                        verbose_name="recette",
                    ),
                ),
                (
                    "saved_meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_plan_entries",
                        to="recipes.savedmeal",
                        verbose_name="repas enregistré",
                    ),
                ),
            ],
            options={
                "verbose_name": "élément planifié",
                "verbose_name_plural": "éléments planifiés",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="mealplan",
            index=models.Index(
                fields=["owner", "-start_date"], name="planning_me_owner_i_9f23de_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mealplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="meal_plan_ordered_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="mealplanday",
            constraint=models.UniqueConstraint(
                fields=("meal_plan", "date"), name="meal_plan_day_unique_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="mealplanentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="meal_plan_entry_positive_quantity"
            ),
        ),
    ]
