# Generated by Django 5.2.9 on 2026-08-25 12:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="poids (kg)",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "pesée",
                "verbose_name_plural": "pesées",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["user", "-date"], name="progress_we_user_id_8e7ca2_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="weight_entry_unique_per_day"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weight_kg__gt", 0)),
                        name="weight_entry_positive_weight",
                    ),
                ],
            },
        ),
    ]
