# Generated by Django 5.2.9 on 2026-08-26 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("progress", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyMeasurementEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "waist_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="tour de taille (cm)",
                    ),
                ),
                (
                    "hips_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="tour de hanches (cm)",
                    ),
                ),
                (
                    "chest_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="tour de poitrine (cm)",
                    ),
                ),
                (
                    "arm_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="tour de bras (cm)",
                    ),
                ),
                (
                    "thigh_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="tour de cuisse (cm)",
                    ),
                ),
                (
                    "body_fat_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="masse grasse (%)",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_measurements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensuration",
                "verbose_name_plural": "mensurations",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["user", "-date"], name="progress_bo_user_id_51dddd_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="body_measurement_unique_per_day"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("waist_cm__isnull", True), ("waist_cm__gt", 0), _connector="OR"
                        ),
                        name="body_measurement_positive_waist_cm",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("hips_cm__isnull", True), ("hips_cm__gt", 0), _connector="OR"
                        ),
                        name="body_measurement_positive_hips_cm",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("chest_cm__isnull", True), ("chest_cm__gt", 0), _connector="OR"
                        ),
                        name="body_measurement_positive_chest_cm",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("arm_cm__isnull", True), ("arm_cm__gt", 0), _connector="OR"
                        ),
                        name="body_measurement_positive_arm_cm",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("thigh_cm__isnull", True), ("thigh_cm__gt", 0), _connector="OR"
                        ),
                        name="body_measurement_positive_thigh_cm",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("body_fat_percent__isnull", True),
                            ("body_fat_percent__gt", 0),
                            _connector="OR",
                        ),
                        name="body_measurement_positive_body_fat_percent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("body_fat_percent__isnull", True),
                            ("body_fat_percent__lte", 100),
                            _connector="OR",
                        ),
                        name="body_measurement_body_fat_at_most_100",
                    ),
                ],
            },
        ),
    ]
