# Generated by Django 5.2.9 on 2026-08-29 17:44

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("progress", "0002_bodymeasuremententry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressPhotoGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "weight_kg_snapshot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Recopié à l'ajout : la pesée peut changer, la photo non.",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("20"))],
                        verbose_name="poids du jour (kg)",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="note")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_photo_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "groupe de photos",
                "verbose_name_plural": "groupes de photos",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ProgressPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("front", "Face"),
                            ("side", "Profil"),
                            ("back", "Dos"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=16,
                        verbose_name="angle",
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(
                        help_text="Non devinable, donc secrète : elle n'apparaît dans aucune réponse d'API.",
                        max_length=255,
                        unique=True,
                        verbose_name="clé de stockage",
                    ),
                ),
                ("mime_type", models.CharField(max_length=64, verbose_name="type")),
                ("size_bytes", models.PositiveIntegerField(verbose_name="taille (octets)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="progress.progressphotogroup",
                        verbose_name="groupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo de progression",
                "verbose_name_plural": "photos de progression",
                "ordering": ["photo_type", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="progressphotogroup",
            index=models.Index(fields=["user", "-date"], name="progress_pr_user_id_06a555_idx"),
        ),
        migrations.AddConstraint(
            model_name="progressphotogroup",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="progress_photo_group_unique_per_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="progressphotogroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("weight_kg_snapshot__isnull", True),
                    ("weight_kg_snapshot__gt", 0),
                    _connector="OR",
                ),
                name="progress_photo_group_positive_weight",
            ),
        ),
    ]
