# Generated by Django 5.2.9 on 2026-08-27 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AITaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("meal_scan", "Analyse de photo de repas")],
                        max_length=32,
                        verbose_name="type de tâche",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "En cours"),
                            ("success", "Réussi"),
                            ("failed", "Échoué"),
                        ],
                        max_length=16,
                        verbose_name="statut",
                    ),
                ),
                ("provider", models.CharField(max_length=32, verbose_name="fournisseur")),
                ("model", models.CharField(max_length=100, verbose_name="modèle")),
                (
                    "input_summary",
                    models.CharField(
                        blank=True,
                        help_text="Description de l'entrée, jamais son contenu.",
                        max_length=255,
                        null=True,
                        verbose_name="résumé de l'entrée",
                    ),
                ),
                (
                    "output_summary",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="résumé de la sortie"
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        help_text="Message nettoyé, sans trace technique ni charge utile.",
                        max_length=255,
                        null=True,
                        verbose_name="erreur",
                    ),
                ),
                (
                    "cost_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="En dollars, si le fournisseur permet de le calculer.",
                        max_digits=10,
                        null=True,
                        verbose_name="coût estimé",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="démarré le")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="terminé le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_task_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "appel IA",
                "verbose_name_plural": "appels IA",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="ai_aitasklo_user_id_fef130_idx"
                    ),
                    models.Index(
                        fields=["task_type", "-created_at"], name="ai_aitasklo_task_ty_c1ca55_idx"
                    ),
                ],
            },
        ),
    ]
