# Generated by Django 5.2.9 on 2026-08-27 21:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_enable_postgres_extensions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True, verbose_name="clé")),
                ("value", models.JSONField(verbose_name="valeur")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
            ],
            options={
                "verbose_name": "réglage",
                "verbose_name_plural": "réglages",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AsyncTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[("meal_scan", "Analyse de photo de repas")],
                        max_length=32,
                        verbose_name="type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("success", "Terminée"),
                            ("failed", "Échouée"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="statut",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(default=0, verbose_name="progression"),
                ),
                ("result", models.JSONField(blank=True, null=True, verbose_name="résultat")),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Message destiné à l'utilisateur, jamais une trace technique.",
                        null=True,
                        verbose_name="erreur",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifiée le")),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="expire le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="async_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "tâche asynchrone",
                "verbose_name_plural": "tâches asynchrones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="common_asyn_user_id_c2f73f_idx"
                    )
                ],
            },
        ),
    ]
