# Generated by Django 5.2.9 on 2026-08-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_app_settings_and_async_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asynctask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("meal_scan", "Analyse de photo de repas"),
                    ("label_scan", "Lecture d'étiquette nutritionnelle"),
                ],
                max_length=32,
                verbose_name="type",
            ),
        ),
    ]
