# Generated by Django 5.2.9 on 2026-08-27 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("rejected", "Refusée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifiée le")),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="demandeur",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande d'amitié",
                "verbose_name_plural": "demandes d'amitié",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["to_user", "status"], name="friend_request_inbox"),
                    models.Index(fields=["from_user", "status"], name="friend_request_outbox"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("from_user", "to_user"),
                        name="friend_request_unique_pending",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("from_user", models.F("to_user")), _negated=True),
                        name="friend_request_not_self",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                (
                    "user_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_as_first",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="premier",
                    ),
                ),
                (
                    "user_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_as_second",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="second",
                    ),
                ),
            ],
            options={
                "verbose_name": "amitié",
                "verbose_name_plural": "amitiés",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_1", "user_2"), name="friendship_unique_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("user_1__lt", models.F("user_2"))),
                        name="friendship_canonical_order",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SharePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("food", "Aliment personnel"),
                            ("recipe", "Recette"),
                            ("saved_meal", "Repas enregistré"),
                            ("diary", "Journal"),
                            ("progress", "Progression"),
                        ],
                        max_length=16,
                        verbose_name="ressource",
                    ),
                ),
                (
                    "resource_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Nul pour le journal et la progression, qui n'en ont pas.",
                        null=True,
                        verbose_name="identifiant de la ressource",
                    ),
                ),
                (
                    "visibility_type",
                    models.CharField(
                        choices=[
                            ("specific_user", "Utilisateur choisi"),
                            ("app_users", "Tous les utilisateurs actifs"),
                        ],
                        max_length=16,
                        verbose_name="portée",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_granted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propriétaire",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nul pour un partage à tous les comptes actifs.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "partage",
                "verbose_name_plural": "partages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_user", "resource_type"], name="share_received_by_type"
                    ),
                    models.Index(fields=["owner", "resource_type"], name="share_granted_by_type"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "target_user", "resource_type", "resource_id"),
                        name="share_unique_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("target_user__isnull", False), ("visibility_type", "specific_user")
                            ),
                            models.Q(
                                ("target_user__isnull", True), ("visibility_type", "app_users")
                            ),
                            _connector="OR",
                        ),
                        name="share_target_matches_visibility",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("owner", models.F("target_user")), _negated=True),
                        name="share_not_to_self",
                    ),
                ],
            },
        ),
    ]
