# Generated by Django 5.2.9 on 2026-08-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharepermission",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("food", "Aliment personnel"),
                    ("recipe", "Recette"),
                    ("saved_meal", "Repas enregistré"),
                    ("shopping_list", "Liste de courses"),
                    ("diary", "Journal"),
                    ("progress", "Progression"),
                ],
                max_length=16,
                verbose_name="ressource",
            ),
        ),
    ]
