# Generated by Django 5.2.9 on 2026-08-29 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """La clé d'unicité des partages porte enfin sur les lignes qui comptent.

    `resource_id` est nul pour tout partage de journal ou de progression, et
    `target_user` pour tout partage global : avec `nulls_distinct` par défaut,
    l'index ne s'appliquait à aucune de ces lignes.
    """

    dependencies = [
        ("social", "0002_alter_sharepermission_resource_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sharepermission",
            name="share_unique_target",
        ),
        migrations.AddConstraint(
            model_name="sharepermission",
            constraint=models.UniqueConstraint(
                fields=("owner", "target_user", "resource_type", "resource_id"),
                name="share_unique_target",
                nulls_distinct=False,
            ),
        ),
    ]
