# Generated by Django 5.2.9 on 2026-08-27 08:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nutrition", "0003_fix_food_portion_unique_nulls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="description"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(blank=True, default="", verbose_name="instructions"),
                ),
                (
                    "servings",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="nombre de portions",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Privé"),
                            ("specific_users", "Utilisateurs choisis"),
                            ("app_users", "Tous les utilisateurs actifs"),
                        ],
                        default="private",
                        max_length=16,
                        verbose_name="visibilité",
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False, verbose_name="favori")),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Suppression douce : les entrées de journal historiques restent valides.",
                        null=True,
                        verbose_name="supprimée le",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifiée le")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propriétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "recette",
                "verbose_name_plural": "recettes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "food_name",
                    models.CharField(
                        help_text="Recopié à l'ajout : l'ingrédient reste lisible si l'aliment disparaît.",
                        max_length=255,
                        verbose_name="nom de l'aliment",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, max_digits=10, verbose_name="quantité"),
                ),
                ("unit_label", models.CharField(max_length=40, verbose_name="unité")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipe_ingredients",
                        to="nutrition.food",
                        verbose_name="aliment",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipes.recipe",
                        verbose_name="recette",
                    ),
                ),
            ],
            options={
                "verbose_name": "ingrédient",
                "verbose_name_plural": "ingrédients",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RecipeNutrition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "energy_kcal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="énergie (kcal)",
                    ),
                ),
                (
                    "protein_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="protéines (g)",
                    ),
                ),
                (
                    "carbohydrates_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="glucides (g)",
                    ),
                ),
                (
                    "fat_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="lipides (g)",
                    ),
                ),
                (
                    "fiber_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="fibres (g)",
                    ),
                ),
                (
                    "sugars_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="sucres (g)",
                    ),
                ),
                (
                    "sodium_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="sodium (mg)",
                    ),
                ),
                (
                    "salt_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="sel (g)",
                    ),
                ),
                (
                    "cholesterol_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="cholestérol (mg)",
                    ),
                ),
                (
                    "potassium_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="potassium (mg)",
                    ),
                ),
                (
                    "calcium_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="calcium (mg)",
                    ),
                ),
                (
                    "iron_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="fer (mg)",
                    ),
                ),
                (
                    "magnesium_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="magnésium (mg)",
                    ),
                ),
                (
                    "vitamin_a_ug",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine A (µg)",
                    ),
                ),
                (
                    "vitamin_b6_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine B6 (mg)",
                    ),
                ),
                (
                    "vitamin_b12_ug",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine B12 (µg)",
                    ),
                ),
                (
                    "vitamin_c_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine C (mg)",
                    ),
                ),
                (
                    "vitamin_d_ug",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine D (µg)",
                    ),
                ),
                (
                    "vitamin_e_mg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine E (mg)",
                    ),
                ),
                (
                    "vitamin_k_ug",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        verbose_name="vitamine K (µg)",
                    ),
                ),
                (
                    "incomplete_nutrients",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Nutriments qu'au moins un ingrédient ne renseigne pas (spec 01 §8).",
                        verbose_name="nutriments partiels",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True, verbose_name="calculé le")),
                (
                    "recipe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition",
                        to="recipes.recipe",
                        verbose_name="recette",
                    ),
                ),
            ],
            options={
                "verbose_name": "valeurs nutritionnelles d'une recette",
                "verbose_name_plural": "valeurs nutritionnelles des recettes",
            },
        ),
        migrations.CreateModel(
            name="SavedMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="description"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Privé"),
                            ("specific_users", "Utilisateurs choisis"),
                            ("app_users", "Tous les utilisateurs actifs"),
                        ],
                        default="private",
                        max_length=16,
                        verbose_name="visibilité",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="supprimé le"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créé le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="modifié le")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_meals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="propriétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "repas enregistré",
                "verbose_name_plural": "repas enregistrés",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SavedMealItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("food", "Aliment"), ("recipe", "Recette")],
                        max_length=16,
                        verbose_name="type",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="Recopié à l'ajout : l'élément reste lisible si sa source disparaît.",
                        max_length=255,
                        verbose_name="nom",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, max_digits=10, verbose_name="quantité"),
                ),
                ("unit_label", models.CharField(max_length=40, verbose_name="unité")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="ordre")),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_meal_items",
                        to="nutrition.food",
                        verbose_name="aliment",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_meal_items",
                        to="recipes.recipe",
                        verbose_name="recette",
                    ),
                ),
                (
                    "saved_meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="recipes.savedmeal",
                        verbose_name="repas",
                    ),
                ),
            ],
            options={
                "verbose_name": "élément de repas",
                "verbose_name_plural": "éléments de repas",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(fields=["owner", "name"], name="recipe_owner_name"),
        ),
        migrations.AddConstraint(
            model_name="recipe",
            constraint=models.CheckConstraint(
                condition=models.Q(("servings__gt", 0)), name="recipe_positive_servings"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="recipe_ingredient_positive_quantity"
            ),
        ),
        migrations.AddIndex(
            model_name="savedmeal",
            index=models.Index(fields=["owner", "name"], name="saved_meal_owner_name"),
        ),
        migrations.AddConstraint(
            model_name="savedmealitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="saved_meal_item_positive_quantity"
            ),
        ),
    ]
